pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    default:
                        items:
                            -
                                method: scaleByHeight
                                arguments:
                                    height: 300
                                    forceResize: true
                        medias: {  }
                        name: default
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1717422145
                        creationDate: 1717421821
                        preserveAnimation: false
