pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    etsy:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 3000
                                    forceResize: true
                        medias: {  }
                        name: etsy
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1717482153
                        creationDate: 1717482120
                        preserveAnimation: false
