pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        language: tr
        valid_languages:
            - tr
            - en
        fallback_languages:
            tr: ''
            en: ''
        default_language: tr
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                en: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
