<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RGHub4nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RGHub4n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RGHub4n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'defaultPreviewGenerator' => ['privates', 'Pimcore\\Model\\DataObject\\ClassDefinition\\PreviewGeneratorInterface', 'getPreviewGeneratorInterfaceService', true],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'defaultPreviewGenerator' => 'Pimcore\\Model\\DataObject\\ClassDefinition\\PreviewGeneratorInterface',
            'eventDispatcher' => '?',
        ]);
    }
}
