<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_FosJsRouting_RouterDebugExposedCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.fos_js_routing.router_debug_exposed_command.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.fos_js_routing.router_debug_exposed_command.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('fos:js-routing:debug', [], 'Displays currently exposed routes for an application', false, #[\Closure(name: 'fos_js_routing.router_debug_exposed_command', class: 'FOS\\JsRoutingBundle\\Command\\RouterDebugExposedCommand')] fn (): \FOS\JsRoutingBundle\Command\RouterDebugExposedCommand => ($container->privates['fos_js_routing.router_debug_exposed_command'] ?? $container->load('getFosJsRouting_RouterDebugExposedCommandService')));
    }
}
