<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HXLWsYsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HXLWsYs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HXLWsYs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['privates', 'Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\Manager', 'getManager2Service', true],
        ], [
            'manager' => 'Pimcore\\Bundle\\AdminBundle\\GDPR\\DataProvider\\Manager',
        ]);
    }
}
