<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4LxmfViService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4LxmfVi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4LxmfVi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'element' => ['privates', '.errored..service_locator.4LxmfVi.Pimcore\\Model\\Element\\ElementInterface', NULL, 'Cannot autowire service ".service_locator.4LxmfVi": it references interface "Pimcore\\Model\\Element\\ElementInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'element' => 'Pimcore\\Model\\Element\\ElementInterface',
        ]);
    }
}
