<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GGvT0fNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gGvT0fN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gGvT0fN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'service' => ['services', 'Pimcore\\Model\\Notification\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'service' => 'Pimcore\\Model\\Notification\\Service\\NotificationService',
        ]);
    }
}
