<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassesDefinitionsBuildCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ClassesDefinitionsBuildCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand(($container->services['Pimcore\\DataObject\\ClassBuilder\\PHPClassDumperInterface'] ?? $container->load('getPHPClassDumperInterfaceService')), ($container->services['Pimcore\\DataObject\\ClassBuilder\\PHPFieldCollectionClassDumperInterface'] ?? $container->load('getPHPFieldCollectionClassDumperInterfaceService')), ($container->services['Pimcore\\DataObject\\ClassBuilder\\PHPObjectBrickClassDumperInterface'] ?? $container->load('getPHPObjectBrickClassDumperInterfaceService')), ($container->services['Pimcore\\DataObject\\ClassBuilder\\PHPObjectBrickContainerClassDumperInterface'] ?? $container->load('getPHPObjectBrickContainerClassDumperInterfaceService')), ($container->services['Pimcore\\DataObject\\ClassBuilder\\PHPSelectOptionsEnumDumperInterface'] ?? $container->load('getPHPSelectOptionsEnumDumperInterfaceService')));

        $instance->setName('pimcore:build:classes');
        $instance->setDescription('rebuilds php files for classes, field collections and object bricks'."\n".'    based on updated var/classes/definition_*.php files');

        return $instance;
    }
}
