<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\SeoBundle\Redirect\Csv' shared autowired service.
     *
     * @return \Pimcore\Bundle\SeoBundle\Redirect\Csv
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Redirect/Csv.php';

        return $container->privates['Pimcore\\Bundle\\SeoBundle\\Redirect\\Csv'] = new \Pimcore\Bundle\SeoBundle\Redirect\Csv();
    }
}
