<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanupCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\Document\CleanupCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\Document\CleanupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/Document/CleanupCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Document\\CleanupCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\Document\CleanupCommand();

        $instance->setName('pimcore:documents:cleanup');
        $instance->setDescription('Cleans up unused document types. Removes type from enums and tables if exist');

        return $instance;
    }
}
