<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteUnusedLocaleDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\DeleteUnusedLocaleDataCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\DeleteUnusedLocaleDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/Traits/DryRun.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/DeleteUnusedLocaleDataCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\DeleteUnusedLocaleDataCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\DeleteUnusedLocaleDataCommand();

        $instance->setName('pimcore:locale:delete-unused-tables');
        $instance->setDescription('Delete unused locale(invalid language) tables & views');

        return $instance;
    }
}
