<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentTreeGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentTreeGenerator' shared autowired service.
     *
     * @return \Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentTreeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/GeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/AbstractElementGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Document/DocumentTreeGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/UrlGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Document/DocumentUrlGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Document/DocumentUrlGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/UrlGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/Filter/PublishedFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/Filter/PropertiesFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Document/Filter/DocumentTypeFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Document/Filter/SiteRootFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/Processor/ModificationDateProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Sitemap/Element/Processor/PropertiesProcessor.php';

        return $container->privates['Pimcore\\Bundle\\SeoBundle\\Sitemap\\Document\\DocumentTreeGenerator'] = new \Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentTreeGenerator(new \Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentUrlGenerator(new \Pimcore\Bundle\SeoBundle\Sitemap\UrlGenerator(($container->services['pimcore.routing.router.request_context'] ?? self::getPimcore_Routing_Router_RequestContextService($container)))), [new \Pimcore\Bundle\SeoBundle\Sitemap\Element\Filter\PublishedFilter(), new \Pimcore\Bundle\SeoBundle\Sitemap\Element\Filter\PropertiesFilter(), new \Pimcore\Bundle\SeoBundle\Sitemap\Document\Filter\DocumentTypeFilter(), new \Pimcore\Bundle\SeoBundle\Sitemap\Document\Filter\SiteRootFilter()], [new \Pimcore\Bundle\SeoBundle\Sitemap\Element\Processor\ModificationDateProcessor(), new \Pimcore\Bundle\SeoBundle\Sitemap\Element\Processor\PropertiesProcessor()]);
    }
}
