<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Maintenance\Executor' shared autowired service.
     *
     * @return \Pimcore\Maintenance\Executor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Executor.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/TaskInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SimpleBackendSearchBundle/src/Task/Maintenance/FullTextIndexOptimizeTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/ApplicationLoggerBundle/src/Maintenance/LogArchiveTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/ApplicationLoggerBundle/src/Maintenance/LogMailMaintenanceTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Maintenance/RedirectCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/Maintenance/LogErrorCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/ScheduledTasksTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LogCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/CleanupBrickTablesTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DataObject/ConcreteTaskHelperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DataObject/CleanupBrickTablesTaskHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DataObject/DataObjectTaskHelperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DataObject/DataObjectTaskHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/CleanupClassificationstoreTablesTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/VersionsCleanupStackTraceDbTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/TmpStoreCleanupTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/HousekeepingTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/LowQualityImagePreviewTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/PruningCacheItemsTask.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Maintenance/Tasks/StaticPagesGenerationTask.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['Pimcore\\Maintenance\\Executor'])) {
            return $container->privates['Pimcore\\Maintenance\\Executor'];
        }
        $b = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        $container->privates['Pimcore\\Maintenance\\Executor'] = $instance = new \Pimcore\Maintenance\Executor('maintenance.pid', $b, $a);

        $c = ($container->services['Symfony\\Component\\Lock\\LockFactory'] ?? self::getLockFactoryService($container));
        $d = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));
        $e = ($container->services['Pimcore\\Config'] ??= new \Pimcore\Config());
        $f = new \Pimcore\Maintenance\Tasks\DataObject\DataObjectTaskHelper($b, $d);

        $instance->registerTask('optimize_fulltext_indexes', new \Pimcore\Bundle\SimpleBackendSearchBundle\Task\Maintenance\FullTextIndexOptimizeTask($c), NULL);
        $instance->registerTask('archiveLogEntries', new \Pimcore\Bundle\ApplicationLoggerBundle\Maintenance\LogArchiveTask($d, $e, $b), NULL);
        $instance->registerTask('logmaintenance', new \Pimcore\Bundle\ApplicationLoggerBundle\Maintenance\LogMailMaintenanceTask($d, $e), NULL);
        $instance->registerTask('redirectcleanup', new \Pimcore\Bundle\SeoBundle\Maintenance\RedirectCleanupTask($b), NULL);
        $instance->registerTask('httperrorlog', new \Pimcore\Bundle\SeoBundle\Maintenance\LogErrorCleanupTask($d), NULL);
        $instance->registerTask('scheduledtasks', new \Pimcore\Maintenance\Tasks\ScheduledTasksTask($b), '\\Pimcore\\Messenger\\ScheduledTaskMessage');
        $instance->registerTask('cleanuplogfiles', new \Pimcore\Maintenance\Tasks\LogCleanupTask(), NULL);
        $instance->registerTask('cleanupBrickTables', new \Pimcore\Maintenance\Tasks\CleanupBrickTablesTask(new \Pimcore\Maintenance\Tasks\DataObject\CleanupBrickTablesTaskHelper($b, $f, $d)), NULL);
        $instance->registerTask('cleanupClassificationstoreTables', new \Pimcore\Maintenance\Tasks\CleanupClassificationstoreTablesTask($b), NULL);
        $instance->registerTask('cleanupFieldcollectionTables', new \Pimcore\Maintenance\Tasks\CleanupFieldcollectionTablesTask(new \Pimcore\Maintenance\Tasks\DataObject\CleanupFieldcollectionTablesTaskHelper($b, $f, $d)), NULL);
        $instance->registerTask('versioncleanup', new \Pimcore\Maintenance\Tasks\VersionsCleanupTask($b, ($container->services['Pimcore\\SystemSettingsConfig'] ?? self::getSystemSettingsConfigService($container))), NULL);
        $instance->registerTask('VersionsCleanupStackTraceDb', new \Pimcore\Maintenance\Tasks\VersionsCleanupStackTraceDbTask($b), NULL);
        $instance->registerTask('cleanupbrokenviews', new \Pimcore\Maintenance\Tasks\DbCleanupBrokenViewsTask($d, $b), NULL);
        $instance->registerTask('tmpstorecleanup', new \Pimcore\Maintenance\Tasks\TmpStoreCleanupTask($d), NULL);
        $instance->registerTask('housekeeping', new \Pimcore\Maintenance\Tasks\HousekeepingTask(7776000, 1800), NULL);
        $instance->registerTask('low_quality_image_preview', new \Pimcore\Maintenance\Tasks\LowQualityImagePreviewTask($b, $c), NULL);
        $instance->registerTask('pruning_cache_items', new \Pimcore\Maintenance\Tasks\PruningCacheItemsTask(($container->services['cache.app'] ?? self::getCache_AppService($container))), NULL);
        $instance->registerTask('documents_static_page_generate', new \Pimcore\Maintenance\Tasks\StaticPagesGenerationTask(($container->services['Pimcore\\Document\\StaticPageGenerator'] ?? self::getStaticPageGeneratorService($container)), $b), NULL);

        return $instance;
    }
}
