<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailLogsCleanupCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\EmailLogsCleanupCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\EmailLogsCleanupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/EmailLogsCleanupCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\EmailLogsCleanupCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\EmailLogsCleanupCommand();

        $instance->setName('pimcore:email:cleanup');
        $instance->setAliases(['email:cleanup']);
        $instance->setDescription('Cleanup email logs');

        return $instance;
    }
}
