<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosJsRouting_RoutesResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_js_routing.routes_response' shared service.
     *
     * @return \FOS\JsRoutingBundle\Response\RoutesResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/jsrouting-bundle/Response/RoutesResponse.php';

        return $container->services['fos_js_routing.routes_response'] = new \FOS\JsRoutingBundle\Response\RoutesResponse();
    }
}
