<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInternalUnicodeCldrLanguageTerritoryGeneratorCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\InternalUnicodeCldrLanguageTerritoryGeneratorCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\InternalUnicodeCldrLanguageTerritoryGeneratorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/InternalUnicodeCldrLanguageTerritoryGeneratorCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\InternalUnicodeCldrLanguageTerritoryGeneratorCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\InternalUnicodeCldrLanguageTerritoryGeneratorCommand(($container->services['Pimcore\\Localization\\LocaleServiceInterface'] ?? self::getLocaleServiceInterfaceService($container)));

        $instance->setName('internal:unicode-cldr-language-territory-generator');
        $instance->setHidden(true);
        $instance->setDescription('For internal use only');

        return $instance;
    }
}
