<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuantityValueCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\Definition\Import\QuantityValueCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\Definition\Import\QuantityValueCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/Traits/DryRun.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/Definition/Import/QuantityValueCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/models/DataObject/QuantityValue/Service.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Definition\\Import\\QuantityValueCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\Definition\Import\QuantityValueCommand(($container->privates['Pimcore\\Model\\DataObject\\QuantityValue\\Service'] ??= new \Pimcore\Model\DataObject\QuantityValue\Service()));

        $instance->setName('pimcore:definition:import:units');
        $instance->setAliases(['definition:import:units']);
        $instance->setDescription('Import quantity value units from a JSON export');

        return $instance;
    }
}
