<?php

namespace ContainerIy42MPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Serializer\Serializer' shared autowired service.
     *
     * @return \Pimcore\Serializer\Serializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Serializer/Serializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Serializer/Normalizer/ReferenceLoopNormalizer.php';

        return $container->services['Pimcore\\Serializer\\Serializer'] = new \Pimcore\Serializer\Serializer([new \Pimcore\Serializer\Normalizer\ReferenceLoopNormalizer()], [new \Symfony\Component\Serializer\Encoder\JsonEncoder()]);
    }
}
