<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: iwapim
 * Date: Thu, 13 Feb 2025 11:46:32 +0000
 */

$conf['title'] = 'IWA Concept';
$conf['lang'] = 'tr';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile_delete';
$conf['userewrite'] = '2';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
