# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 13 Feb 2025 10:59:47 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

iwapim:$2y$10$h0gLu8sD7XuaHkUk2LGFOusA2fblnuxfrUjXNjXeXdJQFypsg3oFe:IWAPIM:iwa@kariyerfora.com:admin,user
iwaconcept:$2y$10$pttdJF3g16UX972K0NYFgei/cCjVPVlradfdi26Xl2Y3J28.8Hj8S:IWACONCEPT:iwa@iwaconcept.com:user
