<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAXlCAK0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAXlCAK0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAXlCAK0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAXlCAK0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAXlCAK0\App_KernelDevDebugContainer([
    'container.build_hash' => 'AXlCAK0',
    'container.build_id' => 'ac765a36',
    'container.build_time' => 1718381393,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAXlCAK0');
