<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5GjWqum\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5GjWqum/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5GjWqum.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5GjWqum\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5GjWqum\App_KernelDevDebugContainer([
    'container.build_hash' => '5GjWqum',
    'container.build_id' => '9ab90077',
    'container.build_time' => 1717620822,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5GjWqum');
