<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'pimcoreAdmin' => 0,
'pimcoreAdminImageEditor' => 1,

], [

0 => [
    'entrypoints' => [
        'admin' => [
            'js' => [
                '/bundles/pimcoreadmin/build/admin/runtime.js',
                '/bundles/pimcoreadmin/build/admin/213.js',
                '/bundles/pimcoreadmin/build/admin/admin.js',
            ],
            'css' => [
                '/bundles/pimcoreadmin/build/admin/admin.css',
            ],
        ],
    ],
],
1 => [
    'entrypoints' => [
        'imageEditor' => [
            'js' => [
                '/bundles/pimcoreadmin/build/imageEditor/runtime.js',
                '/bundles/pimcoreadmin/build/imageEditor/imageEditor.js',
            ],
        ],
    ],
],

]];
