<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MvswpQyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mvswpQy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mvswpQy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'maintenanceModeHelper' => ['services', 'Pimcore\\Tool\\MaintenanceModeHelperInterface', 'getMaintenanceModeHelperInterfaceService', false],
        ], [
            'maintenanceModeHelper' => 'Pimcore\\Tool\\MaintenanceModeHelperInterface',
        ]);
    }
}
