<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vmf_MVOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vmf.MVO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vmf.MVO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'redirectHandler' => ['privates', 'Pimcore\\Bundle\\SeoBundle\\Redirect\\RedirectHandler', 'getRedirectHandlerService', false],
        ], [
            'redirectHandler' => 'Pimcore\\Bundle\\SeoBundle\\Redirect\\RedirectHandler',
        ]);
    }
}
