<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JqXUAW8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jqXUAW8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jqXUAW8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentRenderer' => ['services', 'Pimcore\\Document\\Renderer\\DocumentRendererInterface', 'getDocumentRendererInterfaceService', false],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'documentRenderer' => '?',
            'router' => '?',
        ]);
    }
}
