<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KAPXGPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KAPXGPI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KAPXGPI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'collection' => ['privates', '.errored..service_locator.KAPXGPI.Pimcore\\HttpKernel\\BundleCollection\\BundleCollection', NULL, 'Cannot autowire service ".service_locator.KAPXGPI": it references class "Pimcore\\HttpKernel\\BundleCollection\\BundleCollection" but no such service exists.'],
        ], [
            'collection' => 'Pimcore\\HttpKernel\\BundleCollection\\BundleCollection',
        ]);
    }
}
