<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIByowlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jIByowl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jIByowl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Pimcore\\Http\\Request\\Resolver\\DocumentResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\DocumentResolver', 'getDocumentResolverService', false],
            'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver', 'getEditmodeResolverService', false],
            'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver' => ['services', 'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver', 'getResponseHeaderResolverService', false],
            'Pimcore\\Templating\\Renderer\\EditableRenderer' => ['services', 'Pimcore\\Templating\\Renderer\\EditableRenderer', 'getEditableRendererService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'pimcore.templating' => ['services', 'pimcore.templating.engine.delegating', 'getPimcore_Templating_Engine_DelegatingService', true],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'serializer' => ['privates', 'serializer', 'getSerializer2Service', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'Pimcore\\Http\\Request\\Resolver\\DocumentResolver' => 'Pimcore\\Http\\Request\\Resolver\\DocumentResolver',
            'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver' => 'Pimcore\\Http\\Request\\Resolver\\EditmodeResolver',
            'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver' => 'Pimcore\\Http\\Request\\Resolver\\ResponseHeaderResolver',
            'Pimcore\\Templating\\Renderer\\EditableRenderer' => 'Pimcore\\Templating\\Renderer\\EditableRenderer',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'pimcore.templating' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'twig' => '?',
        ]);
    }
}
