<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6OkMSTRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6OkMSTR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6OkMSTR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csv' => ['privates', 'Pimcore\\Bundle\\SeoBundle\\Redirect\\Csv', 'getCsvService', true],
        ], [
            'csv' => 'Pimcore\\Bundle\\SeoBundle\\Redirect\\Csv',
        ]);
    }
}
