<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationLoggerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pimcore\Bundle\ApplicationLoggerBundle\ApplicationLogger' shared autowired service.
     *
     * @return \Pimcore\Bundle\ApplicationLoggerBundle\ApplicationLogger
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/ApplicationLoggerBundle/src/ApplicationLogger.php';

        $container->services['Pimcore\\Bundle\\ApplicationLoggerBundle\\ApplicationLogger'] = $instance = new \Pimcore\Bundle\ApplicationLoggerBundle\ApplicationLogger();

        $instance->addWriter(($container->services['Pimcore\\Bundle\\ApplicationLoggerBundle\\Handler\\ApplicationLoggerDb'] ?? $container->load('getApplicationLoggerDbService')));

        return $instance;
    }
}
