<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBundleCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KAPXGPI.Pimcore\HttpKernel\BundleCollection\BundleCollection' shared service.
     *
     * @return \Pimcore\HttpKernel\BundleCollection\BundleCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KAPXGPI": it references class "Pimcore\\HttpKernel\\BundleCollection\\BundleCollection" but no such service exists.');
    }
}
