<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassesDefinitionsBuildCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\ClassesDefinitionsBuildCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:build:classes', [], 'rebuilds php files for classes, field collections and object bricks'."\n".'    based on updated var/classes/definition_*.php files', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\ClassesDefinitionsBuildCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\ClassesDefinitionsBuildCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ClassesDefinitionsBuildCommand'] ?? $container->load('getClassesDefinitionsBuildCommandService')));
    }
}
