<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteClassificationStoreCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\DeleteClassificationStoreCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\DeleteClassificationStoreCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/DeleteClassificationStoreCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\DeleteClassificationStoreCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\DeleteClassificationStoreCommand();

        $instance->setName('pimcore:classificationstore:delete-store');
        $instance->setAliases(['classificationstore:delete-store']);
        $instance->setDescription('Delete Classification Store');

        return $instance;
    }
}
