<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementServiceInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\AdminBundle\Service\ElementServiceInterface' shared autowired service.
     *
     * @return \Pimcore\Bundle\AdminBundle\Service\ElementService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/admin-ui-classic-bundle/src/Service/ElementServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Traits/AdminStyleTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/admin-ui-classic-bundle/src/Service/ElementService.php';

        return $container->privates['Pimcore\\Bundle\\AdminBundle\\Service\\ElementServiceInterface'] = new \Pimcore\Bundle\AdminBundle\Service\ElementService(($container->services['router'] ?? self::getRouterService($container)), ($container->services['Pimcore\\Config'] ??= new \Pimcore\Config()), ($container->privates['Pimcore\\Security\\User\\UserLoader'] ?? self::getUserLoaderService($container)));
    }
}
