<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4LxmfVi.Pimcore\Model\Element\ElementInterface' shared service.
     *
     * @return \Pimcore\Model\Element\ElementInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4LxmfVi": it references interface "Pimcore\\Model\\Element\\ElementInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
