<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLowQualityImagePreviewCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\LowQualityImagePreviewCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\LowQualityImagePreviewCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:image:low-quality-preview', ['pimcore:image:svg-preview'], 'Regenerates low-quality image previews for all image assets', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\LowQualityImagePreviewCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\LowQualityImagePreviewCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\LowQualityImagePreviewCommand'] ?? $container->load('getLowQualityImagePreviewCommandService')));
    }
}
