<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLowQualityImagePreviewCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\LowQualityImagePreviewCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\LowQualityImagePreviewCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/LowQualityImagePreviewCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\LowQualityImagePreviewCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\LowQualityImagePreviewCommand();

        $instance->setName('pimcore:image:low-quality-preview');
        $instance->setAliases(['pimcore:image:svg-preview']);
        $instance->setDescription('Regenerates low-quality image previews for all image assets');

        return $instance;
    }
}
