<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcore_Class_Resolver_DocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pimcore.class.resolver.document' shared autowired service.
     *
     * @return \Pimcore\Resolver\ClassResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Resolver/ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Resolver/ClassResolver.php';

        return $container->services['pimcore.class.resolver.document'] = new \Pimcore\Resolver\ClassResolver($container->parameters['pimcore.documents.classes.map']);
    }
}
