<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunScriptCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\RunScriptCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\RunScriptCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:run-script', [], 'Run a specific PHP script in an initialized Pimcore environment', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\RunScriptCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\RunScriptCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\RunScriptCommand'] ?? $container->load('getRunScriptCommandService')));
    }
}
