<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseExceptionListener2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\SeoBundle\EventListener\ResponseExceptionListener' shared autowired service.
     *
     * @return \Pimcore\Bundle\SeoBundle\EventListener\ResponseExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/EventListener/ResponseExceptionListener.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->privates['Pimcore\\Bundle\\SeoBundle\\EventListener\\ResponseExceptionListener'])) {
            return $container->privates['Pimcore\\Bundle\\SeoBundle\\EventListener\\ResponseExceptionListener'];
        }

        $container->privates['Pimcore\\Bundle\\SeoBundle\\EventListener\\ResponseExceptionListener'] = $instance = new \Pimcore\Bundle\SeoBundle\EventListener\ResponseExceptionListener($a);

        $instance->setPimcoreContextResolver(($container->services['Pimcore\\Http\\Request\\Resolver\\PimcoreContextResolver'] ?? self::getPimcoreContextResolverService($container)));

        return $instance;
    }
}
