<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\ResetPasswordCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\ResetPasswordCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/ResetPasswordCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ResetPasswordCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\ResetPasswordCommand();

        $instance->setName('pimcore:user:reset-password');
        $instance->setAliases(['reset-password']);
        $instance->setDescription('Reset a user\'s password');

        return $instance;
    }
}
