<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecyclebinCleanupCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\RecyclebinCleanupCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\RecyclebinCleanupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/RecyclebinCleanupCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\RecyclebinCleanupCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\RecyclebinCleanupCommand();

        $instance->setName('pimcore:recyclebin:cleanup');
        $instance->setDescription('Cleanup recyclebin entries');

        return $instance;
    }
}
