<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRunScriptCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\RunScriptCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\RunScriptCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/Traits/DryRun.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/RunScriptCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\RunScriptCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\RunScriptCommand();

        $instance->setName('pimcore:run-script');
        $instance->setDescription('Run a specific PHP script in an initialized Pimcore environment');

        return $instance;
    }
}
