<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveCustomSettingCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\Asset\RemoveCustomSettingCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\RemoveCustomSettingCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:assets:remove-custom-setting', [], 'Removes a custom setting from assets', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\RemoveCustomSettingCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\Asset\RemoveCustomSettingCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Asset\\RemoveCustomSettingCommand'] ?? $container->load('getRemoveCustomSettingCommandService')));
    }
}
