<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSitemapGeneratorListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\SeoBundle\EventListener\SitemapGeneratorListener' shared autowired service.
     *
     * @return \Pimcore\Bundle\SeoBundle\EventListener\SitemapGeneratorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/SeoBundle/src/EventListener/SitemapGeneratorListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/DependencyInjection/ServiceCollection.php';

        return $container->privates['Pimcore\\Bundle\\SeoBundle\\EventListener\\SitemapGeneratorListener'] = new \Pimcore\Bundle\SeoBundle\EventListener\SitemapGeneratorListener(new \Pimcore\DependencyInjection\ServiceCollection(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pimcore_documents' => ['privates', 'Pimcore\\Bundle\\SeoBundle\\Sitemap\\Document\\DocumentTreeGenerator', 'getDocumentTreeGeneratorService', true],
        ], [
            'pimcore_documents' => '?',
        ]), ['pimcore_documents']));
    }
}
