<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStorageCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Pimcore\Bundle\CoreBundle\Command\Migrate\StorageCommand' shared autowired service.
     *
     * @return \Pimcore\Bundle\CoreBundle\Command\Migrate\StorageCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/Migrate/StorageCommand.php';

        $container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\StorageCommand'] = $instance = new \Pimcore\Bundle\CoreBundle\Command\Migrate\StorageCommand(($container->privates['.service_locator.j55CNh_'] ?? $container->load('get_ServiceLocator_J55CNhService')));

        $instance->setName('pimcore:migrate:storage');
        $instance->setDescription('Migrate data from one storage to another');

        return $instance;
    }
}
