<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThumbnailsFolderStructureCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\Migrate\ThumbnailsFolderStructureCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\ThumbnailsFolderStructureCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:migrate:thumbnails-folder-structure', [], 'Change thumbnail folder structure to'."\n".'    <asset storage>/<path to asset>/<asset id>/image-thumb__<asset id>__<thumbnail name>/<asset filename>'."\n".'    instead of'."\n".'    <asset storage>/<path to asset>/image-thumb__<asset id>__<thumbnail name>/<asset filename>', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\ThumbnailsFolderStructureCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\Migrate\ThumbnailsFolderStructureCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\Migrate\\ThumbnailsFolderStructureCommand'] ?? $container->load('getThumbnailsFolderStructureCommandService')));
    }
}
