<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThumbnailsVideoCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\ThumbnailsVideoCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\ThumbnailsVideoCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:thumbnails:video', ['thumbnails:video'], 'Generate video thumbnails, useful to pre-generate thumbnails in the background', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\ThumbnailsVideoCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\ThumbnailsVideoCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ThumbnailsVideoCommand'] ?? $container->load('getThumbnailsVideoCommandService')));
    }
}
