<?php

namespace ContainerZwWEdmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThumbnailsImageCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Pimcore\Bundle\CoreBundle\Command\ThumbnailsImageCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Pimcore\\Bundle\\CoreBundle\\Command\\ThumbnailsImageCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pimcore:thumbnails:image', ['thumbnails:image'], 'Generate image thumbnails, useful to pre-generate thumbnails in the background', false, #[\Closure(name: 'Pimcore\\Bundle\\CoreBundle\\Command\\ThumbnailsImageCommand')] fn (): \Pimcore\Bundle\CoreBundle\Command\ThumbnailsImageCommand => ($container->privates['Pimcore\\Bundle\\CoreBundle\\Command\\ThumbnailsImageCommand'] ?? $container->load('getThumbnailsImageCommandService')));
    }
}
